#! /usr/bin/bash

# Check if the user passed a name as a command-line argument
if [ -z "$1" ]; then
  echo "No bucket name provided!"
  exit 1

fi


aws s3api create-bucket --bucket $1 --create-bucket-configuration="LocationConstraint=eu-west-2"